apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: hc-asm-gateway
  namespace: gateway
spec:
  default:
    logConfig:
      enabled: true
    config:
      type: HTTP
      httpHealthCheck:
        port: 15021
        requestPath: /healthz/ready
  targetRef:
    group: ""
    kind: Service
    name: istio-ingressgateway